// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Qtdv_-YDe3iVV1DS9Wp7eW67_e-JprU',
    appId: '1:927178680548:web:d89a2b3f8b9c1753b5a4f1',
    messagingSenderId: '927178680548',
    projectId: 'bigproject-825',
    authDomain: 'bigproject-825.firebaseapp.com',
    storageBucket: 'bigproject-825.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE8bMBT6WrHRCCRCMaaeSxAZX-Oh2jxEM',
    appId: '1:927178680548:android:8b425f9c787aeda3b5a4f1',
    messagingSenderId: '927178680548',
    projectId: 'bigproject-825',
    storageBucket: 'bigproject-825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFhLlLe0I7LFyMa7KHi3ahr3A_B8EV3rM',
    appId: '1:927178680548:ios:97fb763b7a120700b5a4f1',
    messagingSenderId: '927178680548',
    projectId: 'bigproject-825',
    storageBucket: 'bigproject-825.firebasestorage.app',
    iosBundleId: 'com.example.bigproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFhLlLe0I7LFyMa7KHi3ahr3A_B8EV3rM',
    appId: '1:927178680548:ios:97fb763b7a120700b5a4f1',
    messagingSenderId: '927178680548',
    projectId: 'bigproject-825',
    storageBucket: 'bigproject-825.firebasestorage.app',
    iosBundleId: 'com.example.bigproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Qtdv_-YDe3iVV1DS9Wp7eW67_e-JprU',
    appId: '1:927178680548:web:f95d48f3bcdb04ddb5a4f1',
    messagingSenderId: '927178680548',
    projectId: 'bigproject-825',
    authDomain: 'bigproject-825.firebaseapp.com',
    storageBucket: 'bigproject-825.firebasestorage.app',
  );
}
